CONFIG_ZMK_KEYBOARD_NAME="Jenny40 Mod"
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Logging helps if TrackPoint does not move.
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOGGING_MINIMAL=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
